### ISSUE TITLE
CLI alternative

### ISSUE THREAD

**Issue by joyrexus** [andreaspitzer/literature#3]
FWIW, as a bash function:

```
literature () {
     grep '^    ' $1 | sed 's/^    //'
}
```

**Comment by andreaspitzer** [comment]
:+1:  That's a reasonable thought and a good solution based on that, @joyrexus - thank you.

I think it will work in many cases where there are no issues with Markdown when stripping the indentation is in conflict with actual content, most likely with [lists](http://daringfireball.net/projects/markdown/syntax#list); my approach to that was to rely on a Markdown parser doing the parsing.

**Comment by joyrexus** [comment]
Good point regarding lists.  Constraining the grep pattern would probably address most of the potential conflicts, but still not robust enough for all edge cases:

``` bash
literature () {
     grep '^    [a-z]' $1 | sed 's/^    //'
}
```

**Comment by andreaspitzer** [comment]
I see preprocessing files to extract code blocks as first step towards a more ambitious vision. The final goal of this project would be to make literate code `import`/`require`able so that no preprocessing step is needed, just like CoffeeScript does (see issue #1).

Please feel free to re-open this issue to contribute more code and further examples, @joyrexus!

Thank you!
All the best, Andreas
